### PR TITLE
Issue #253 and other layout and styling fixes.

### PR DESCRIPTION
**Pull request by mitchas**

### CODE REVIEW

**Comment by harper-wavra** [comment]
Looks good! The only thing I noticed was the manage citations modal is still a little wonky when you filter it.
image

**Comment by harper-wavra** [comment]
It seems to look just a little bit off when the scroll bar is available, it seems to push the columns to the left a little bit, and when the citation is less than a full line of text (which is only our test citations so I don't think really this matters.) Might have to see what @kjacobsen16 thinks, but I think it looks good.

[scroll bar](https://user-images.githubusercontent.com/59063181/92256688-a55d8d00-ee99-11ea-93cb-9c0df350a3b7.png)
[less than full line of text](https://user-images.githubusercontent.com/59063181/92256721-b1494f00-ee99-11ea-817c-f8545d8e1548.png)

**Comment by kjacobsen16** [comment]
@mitchas one more thing I noticed - our form validation styling seems to have been removed. To replicate: log in, go to Settings, click on Agencies, "Add New Agency", then start typing in the Name field and remove the text. You should see this text below:
image

Originally, the input box would have a red outline around it, and the text underneath would be red. I believe we were using the `form-invalid`, etc. classes. They should all be in the html still.

**Review by kjacobsen16 — COMMENTED** [review]
Looks good! I made a couple quick edits, but there are two more items that should be fixed:
1. The main NSS page is only printing one page. To replicate: on main page, select any region, put values in for each explanatory variable, hit "compute", then try to print the page.
2. The map is overlapping a button in the Add Regression Region modal. To replicate: log in, in the main page hit the plus icon next to "limit by hydrologic region", click the button at the bottom that says "Upload Polygon".
image

If you want, we can make those a separate issue.

**Review by harper-wavra — APPROVED** [review]
Looks good, going to merge and create a new issue with the two things KJ noticed.

**Pull request merged**
