### PR TITLE
Fixes #72

### LINKED ISSUE #72: Dealing with short name underscores in MathJax
The equation render seems to be slow when rendering the equations, I think they are kinda fun. But any parameter that has an underscore in the short name loses it's underscore and causes the next letter after the underscore to render as a subscript. You may already be aware of it and have no recourse

### PR DESCRIPTION
**Pull request by harper-wavra**

### CODE REVIEW

**Review by kjacobsen16 — CHANGES_REQUESTED** [review]
Can you replicate this for the mathjax shown after computing scenarios in the main page? Looks good for edit scenario display!

**Comment by harper-wavra** [comment]
I think I fixed where you were talking about, let me know if there is another place. @kjacobsen16 
image

**Comment by harper-wavra** [comment]
Mathjax loads quick after compute now, however I am not sure creating a new function just to pass back is the best way?

**Review by kjacobsen16 — APPROVED** [review]
Looks good

**Pull request merged**
