### PR TITLE
Kd 278 - Changes labels to 'Explanatory Variable' 

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by harper-wavra — CHANGES_REQUESTED** [review]
There are still a couple places in the `mainview.component.html` where there is still the Parameter/Parameters label. 

If you do (Ctrl + Shift + F) in VSCode you can search for specific words. 

[image](https://user-images.githubusercontent.com/59063181/92750327-9456c500-f34c-11ea-895f-34335fcc39f7.png)
[image](https://user-images.githubusercontent.com/59063181/92750425-a89ac200-f34c-11ea-9026-4e2eaff1f2e6.png)

**Comment by ghost** [comment]
Ah, that is true. I only changed the ones singled out in the issue. I'll push it back up in a few mins!

**Comment by ghost** [comment]
Alright, I think I got them all now :)

**Review by harper-wavra — APPROVED** [review]
Looks good 👍

**Pull request merged**
